flags: {}
packages:
- '.'
- location:
    git: git@github.com:aaronlevin/servant.git
    commit: 8bc19df46990357c1380c1eb8a0733e7e6696261
  subdirs:
    - servant
    - servant-server
resolver: nightly-2015-07-24
